Pull request template
nibmfossc/playground pull request #6
Opened 2023-03-28 12:49 UTC by Hirushan-N

2023-03-28 15:10 UTC, dileepadev-old commented on .github/pull_request_template.md
> +<!-- A clear and concise description of the feature. -->
Add details

2023-03-28 15:10 UTC, dileepadev-old commented on .github/pull_request_template.md
> +<!-- List any related issues that the feature addresses or solves. -->
Add details

2023-03-28 15:11 UTC, dileepabandara commented on .github/pull_request_template.md
> +<!-- Describe the changes made to implement the feature. -->
Add details

2023-03-28 15:11 UTC, dileepadev-old commented on .github/pull_request_template.md
> +<!-- Include any relevant screenshots or GIFs to demonstrate the feature. -->
Add details

2023-03-28 15:11 UTC, dileepadev-old commented on .github/pull_request_template.md
> +<!-- Is there anything else that you would like to mention about these changes? For example, do they require any additional steps or documentation for future maintenance? -->
Add details

2023-03-28 15:12 UTC, dileepabandara requested changes
@Hirushan-N Can you please add more details and point out the PR descriptions. 😊

2023-03-30 15:39 UTC, Hirushan-N commented on .github/pull_request_template.md
> +<!-- A clear and concise description of the feature. -->
Dit it

2023-03-30 15:39 UTC, Hirushan-N commented on .github/pull_request_template.md
> +<!-- List any related issues that the feature addresses or solves. -->
Dit it

2023-03-30 15:40 UTC, Hirushan-N commented on .github/pull_request_template.md
> +<!-- Describe the changes made to implement the feature. -->
Dit it

2023-03-30 15:40 UTC, Hirushan-N commented on .github/pull_request_template.md
> +<!-- Include any relevant screenshots or GIFs to demonstrate the feature. -->
Dit it

2023-03-30 15:40 UTC, Hirushan-N commented on .github/pull_request_template.md
> +<!-- Is there anything else that you would like to mention about these changes? For example, do they require any additional steps or documentation for future maintenance? -->
Dit it

2023-03-30 18:12 UTC, dileepabandara approved these changes
Good contribution. @Hirushan-N 👍🏼🥳

2023-03-30 18:12 UTC, merged